In [1]:
from corrosions import Sync

In [2]:
sync = Sync(
    area="Bogor",
    segment="Jonggol-Cimanggis",
    year=2024,
    pipe_diameter=16,
    length=9.95,
    normalized_acvg_dcvg_file=r"D:\Projects\corrosions\tests\normalize\acvg_dcvg\excel\acvg-dcvg-jonggol-cimanggis-16-sheet1.xlsx",
    normalized_cips_file=r"D:\Projects\corrosions\tests\normalize\cips\excel\cips-bgr-16-inch-jonggol-cimanggis-9-95-km-survey-data.xlsx",
    normalized_pcm_file=r"D:\Projects\corrosions\tests\normalize\pcm\excel\pcm-bgr-16-inch-jonggol-cimanggis-9-95-km-sequential-file.xlsx",
    verbose=True,
)

In [3]:
sync

In [4]:
sync.dict

{'year': 2024,
 'area': 'Bogor',
 'segment': 'Jonggol-Cimanggis',
 'pipe_diameter': 16,
 'length': 9.95,
 'files': {'acvg_dcvg': 'D:\\Projects\\corrosions\\tests\\normalize\\acvg_dcvg\\excel\\acvg-dcvg-jonggol-cimanggis-16-sheet1.xlsx',
  'pcm': 'D:\\Projects\\corrosions\\tests\\normalize\\pcm\\excel\\pcm-bgr-16-inch-jonggol-cimanggis-9-95-km-sequential-file.xlsx',
  'cips': 'D:\\Projects\\corrosions\\tests\\normalize\\cips\\excel\\cips-bgr-16-inch-jonggol-cimanggis-9-95-km-survey-data.xlsx'}}

In [5]:
df_acvg = sync.df_acvg_dcvg

In [6]:
df_acvg

,segment_code,diameter,anomaly_location,surface_condition,drop_pcm,on_potential,off_potential,survey_dcvg,survey_acvg,latitude,...,protection,comment,uncertain,uncertain_description,real_distance,closest_pcm_distance,closest_pcm_index,closest_pcm_latitude,closest_pcm_longitude,closest_pcm_real_distance
0,jonggol-cimanggis-16,16,depan Huben Inside,beton trotoar,NaN,-1.00088,NaN,45457,45445,-6.375833,...,NaN,NaN,NaN,NaN,1990.180203,-13.566231,137,-6.375711,106.905360,1976.613972
1,jonggol-cimanggis-16,16,depan jual durian/Manna & Salwa,beton,NaN,-0.93930,NaN,45457,45445,-6.375861,...,NaN,NaN,NaN,NaN,2112.778907,-7.051543,145,-6.375846,106.906494,2105.727365
2,jonggol-cimanggis-16,16,depan tulis MR DIY,trotoar beton,NaN,-0.92921,NaN,45457,45445,-6.375389,...,NaN,NaN,NaN,NaN,3105.887565,-10.240923,207,-6.375473,106.915240,3095.646643
3,jonggol-cimanggis-16,16,depan Ramayana Prime,trotoar,NaN,-0.91251,NaN,45457,45445,-6.375500,...,NaN,NaN,NaN,NaN,3128.781165,-1.024869,209,-6.375491,106.915530,3127.756296
4,jonggol-cimanggis-16,16,depan Sate & Sop Kita,beton,NaN,-0.92539,NaN,45457,45445,-6.376799,...,NaN,NaN,NaN,NaN,3472.072852,-10.850773,233,-6.376702,106.918236,3461.222079
5,jonggol-cimanggis-16,16,depan Bank DMM,parit,NaN,-0.75544,NaN,45457,45445,-6.378194,...,NaN,NaN,NaN,NaN,3795.408293,-5.695961,258,-6.378242,106.920760,3789.712332
6,jonggol-cimanggis-16,16,sebrang THRILL SPILL CUSTOM,beton,NaN,-0.99236,NaN,45457,45445,-6.403722,...,NaN,NaN,NaN,NaN,9862.991956,-2.226592,700,-6.403731,106.960760,9860.765364
7,jonggol-cimanggis-16,16,NaN,NaN,NaN,-0.96418,NaN,45457,45445,-6.404611,...,NaN,NaN,NaN,NaN,10083.670909,-7.656975,717,-6.404544,106.962456,10076.013934

In [7]:
df_cips = sync.df_cips

In [8]:
df_cips.head()

,Voltage,Latitude,Longitude,Comment,DCP/Feature/DCVG Anomaly,protection,condition,voltage_inverse,type,interpolated,Distance,Real Distance
Data No,,,,,,,,,,,,
460802,-0.93548,-6.383329,106.894376,Stasiun Gas Pembagi Cimanggis 2,Test Station,SACP,PROTECTED,0.93548,CIPS,False,0.000000,41.861059
460801,-0.63142,-6.383319,106.894383,NaN,NaN,SACP,UNPROTECTED,0.63142,CIPS,False,1.320255,43.181315
460800,-0.66951,-6.383312,106.894389,NaN,NaN,SACP,UNPROTECTED,0.66951,CIPS,False,1.036657,44.217972
460799,-0.43712,-6.383302,106.894390,NaN,NaN,SACP,UNPROTECTED,0.43712,CIPS,False,1.174643,45.392615
460798,-0.47156,-6.383292,106.894395,NaN,NaN,SACP,UNPROTECTED,0.47156,CIPS,False,1.167545,46.560160

In [9]:
df_pcm = sync.df_pcm

In [10]:
df_pcm.head()

,Start Symbol,Format,Version,PCMx Operating mode,Locator Frequency,Alpha display,Depth (m),Depth (ft),Depth to pipe center (m),Depth to pipe center (ft),...,Ext GPS no. of satellites,Ext GPS dilution,Ext GPS altitude,Pipe Diameter,Survey name (0-100),Comment (0-100),dbma,Distance,Real Distance,Direction
Index,,,,,,,,,,,,,,,,,,,,,
6904,PCMx,9,1,19,512,LFCD,1.68,5.511811,1.8848,6.183727,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,Stasiun Gas Pembagi Cimanggis 2,39.490234,10.562922,0.000000,DECREASING
6903,PCMx,9,1,19,512,LFCD,1.74,5.708662,1.9448,6.380578,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.627310,12.770280,10.562922,DECREASING
6902,PCMx,9,1,19,512,LFCD,1.66,5.446194,1.8648,6.118110,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.806777,11.897857,23.333202,DECREASING
6901,PCMx,9,1,19,512,LFCD,1.70,5.577428,1.9048,6.249344,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.895139,11.553697,35.231059,DECREASING
6900,PCMx,9,1,19,512,LFCD,1.66,5.446194,1.8648,6.118110,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.545324,12.895244,46.784756,DECREASING

In [11]:
sync.first_pcm_coordinates

(np.float64(-6.382967), np.float64(106.89448))

In [12]:
sync.matrix_distance_cips

{'first_first': 41.86105940219567,
 'first_last': 7931.82708056572,
 'last_first': 7884.246632909945,
 'last_last': 46.42079285450626}

In [13]:
sync.matrix_distance_acvg_dcvg

{'first_first': 1440.5148130661019,
 'first_last': 7889.391345209592,
 'last_first': 7070.965297877813,
 'last_last': 7.656975486643989}

In [14]:
sync.fix()

PCM and CIPS are sync

In [15]:
sync.df_pcm

,Start Symbol,Format,Version,PCMx Operating mode,Locator Frequency,Alpha display,Depth (m),Depth (ft),Depth to pipe center (m),Depth to pipe center (ft),...,Ext GPS no. of satellites,Ext GPS dilution,Ext GPS altitude,Pipe Diameter,Survey name (0-100),Comment (0-100),dbma,Distance,Real Distance,Direction
Index,,,,,,,,,,,,,,,,,,,,,
6904,PCMx,9,1,19,512,LFCD,1.68,5.511811,1.8848,6.183727,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,Stasiun Gas Pembagi Cimanggis 2,39.490234,10.562922,0.000000,DECREASING
6903,PCMx,9,1,19,512,LFCD,1.74,5.708662,1.9448,6.380578,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.627310,12.770280,10.562922,DECREASING
6902,PCMx,9,1,19,512,LFCD,1.66,5.446194,1.8648,6.118110,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.806777,11.897857,23.333202,DECREASING
6901,PCMx,9,1,19,512,LFCD,1.70,5.577428,1.9048,6.249344,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.895139,11.553697,35.231059,DECREASING
6900,PCMx,9,1,19,512,LFCD,1.66,5.446194,1.8648,6.118110,...,0,0,0,0.4096,BGR 16 INCH ( JONGGOL CIMANGGIS) P6,NaN,39.545324,12.895244,46.784756,DECREASING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6567,PCMx,9,1,19,640,LFCD,2.76,9.055119,2.9648,9.727034,...,0,0,0,0.4096,BGR 16 JONGGOL CIMANGGIS p4,NaN,25.436832,12.905536,10030.502384,INCREASING
6566,PCMx,9,1,19,640,LFCD,1.45,4.757218,1.6548,5.429134,...,0,0,0,0.4096,BGR 16 JONGGOL CIMANGGIS p4,NaN,37.443126,9.327265,10043.407920,INCREASING
6565,PCMx,9,1,19,640,LFCD,2.87,9.416010,3.0748,10.087926,...,0,0,0,0.4096,BGR 16 JONGGOL CIMANGGIS p4,NaN,23.806634,14.733377,10052.735185,INCREASING
6564,PCMx,9,1,19,640,LFCD,0.92,3.018373,1.1248,3.690289,...,0,0,0,0.4096,BGR 16 JONGGOL CIMANGGIS p4,NaN,16.521496,8.545371,10067.468563,INCREASING
6563,PCMx,9,1,19,640,LFCD,0.78,2.559055,0.9848,3.230971,...,0,0,0,0.4096,BGR 16 JONGGOL CIMANGGIS p4,Tx : 1 A,11.595672,0.000000,10076.013934,INCREASING

In [16]:
sync.recalculate_distance()

Sync is done.

In [17]:
sync.df_cips.iloc[0]

Voltage                                            -0.93548
Latitude                                          -6.383329
Longitude                                        106.894376
Comment                     Stasiun Gas Pembagi Cimanggis 2
DCP/Feature/DCVG Anomaly                       Test Station
protection                                             SACP
condition                                         PROTECTED
voltage_inverse                                     0.93548
type                                                   CIPS
interpolated                                          False
Distance                                                0.0
Real Distance                                     41.861059
Name: 460802, dtype: object

In [18]:
sync.df_pcm.iloc[-1]

Start Symbol                                        PCMx
Format                                                 9
Version                                                1
PCMx Operating mode                                   19
Locator Frequency                                    640
Alpha display                                      LFCD
Depth (m)                                           0.78
Depth (ft)                                      2.559055
Depth to pipe center (m)                          0.9848
Depth to pipe center (ft)                       3.230971
dBuV                                                  -1
Locate current A                                  0.0123
4 Hz Voltage phase                                    -1
Signal strength                                    0.512
Gain (dB)                                             39
MF Foot attached                                       0
4Hz C-V Phase                                         -1
4Hz Current (A)                                   0.0038
Current 4-8Hz Phase                                  0.0
RTC day                                                2
RTC month                                              6
RTC year                                            2024
UTC                                                41638
RTC Updated flag                                       1
Int GPS mode                                           0
Int GPS Latitude                               -6.404544
Int GPS Longitude                             106.962456
Int GPS Fix                                            1
Int GPS no. of satellites                             12
Int GPS dilution                                    0.63
Int GPS altitude                               98.300003
Ext GPS Latitude                                     NaN
Ext GPS Longitude                                    NaN
Ext GPS Fix                                            0
Ext GPS no. of satellites                              0
Ext GPS dilution                                       0
Ext GPS altitude                                       0
Pipe Diameter                                     0.4096
Survey name (0-100)          BGR 16 JONGGOL CIMANGGIS p4
Comment (0-100)                                 Tx : 1 A
dbma                                           11.595672
Distance                                             0.0
Real Distance                               10076.013934
Direction                                     INCREASING
Name: 6563, dtype: object